bookers2/config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  get '/search/:category' => 'search#search_category',as: 'search_category'
  get '/search_date' => 'search#search_date',as: 'search_date'

  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/top' => 'homes#top'
  get '/home/about' => 'homes#about'

  resources :books,only:[:create,:index,:edit,:update,:destroy,:show] do
    resources :book_comments,only:[:create,:destroy]
    resource :favorites,only:[:create,:destroy]
 end

  resources :users,only:[:show,:index,:edit,:update,:destroy] do
    resource :relationships,only:[:create,:destroy]

    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end

 resources :groups do
   resources :group_users,only:[:create,:destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
 end

 resources :messages, only:[:create]
 resources :rooms, only:[:create,:show]
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  is_impressionable counter_cache: true

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user, dependent: :destroy
  validates :title,presence: true
  validates :body,presence: true, length: { maximum: 200 }
 


def favorite_by?(user)
  favorites.where(user_id: user.id).exists?
end

scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }

scope :created_2days_ago, -> { where(created_at: 2.day.ago.all_day) }
scope :created_3days_ago, -> { where(created_at: 3.day.ago.all_day) }
scope :created_4days_ago, -> { where(created_at: 4.day.ago.all_day) }
scope :created_5days_ago, -> { where(created_at: 5.day.ago.all_day) }
scope :created_6days_ago, -> { where(created_at: 6.day.ago.all_day) }


scope :created_this_week, -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)}
scope :created_last_week, -> {where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day)}
end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment ,presence: true
end

bookers2/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2/app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  attachment :image

  def joined_by?(user)
    group_users.where(user_id: user.id).exists?
  end

end

bookers2/app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

bookers2/app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :content ,presence: true, length: { maximum: 200 }
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers2/app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many:entries, dependent: :destroy
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users
  has_many :groups,through: :group_users
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy


  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

  def followed_by?(user)
    followers.include?(user)
  end


  scope :created_this_week, -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)}

  attachment :profile_image

  validates :name,presence: true, length: { minimum: 2 , maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

impressionist :actions=> [:show,:index]

  def show
    @book_s = Book.new
    @book = Book.find(params[:id])
    impressionist(@book, nil, unique: [:ip_address])
    @user = User.find(current_user.id)
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @user = User.find(current_user.id)


    if params[:sort_new]
      @books = Book.order(created_at: "desc")
    elsif params[:sort_rate]
      @books= Book.order(rate: "DESC")
    elsif params[:sort_rank]
      @books = Book.order(impressions_count: "DESC")
    else
      @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    flash[:notice]= "You have created book successfully"
    else
    @books = Book.all
    @user = User.find(current_user.id)
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice]= "You have updated book successfully"
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to user_path(book.user)
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:rate,:category)
  end


end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
    @book_today = @books.created_today
    @book_yesterday = @books.created_yesterday
    @book_this_week = @books.created_this_week
    @book_last_week = @books.created_last_week

    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice]= "You have updated user successfully"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/group_users_helper.rb
module GroupUsersHelper
end

bookers2/app/helpers/groups_helper.rb
module GroupsHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/messages_helper.rb
module MessagesHelper
end

bookers2/app/helpers/rooms_helper.rb
module RoomsHelper
end

bookers2/app/helpers/search_helper.rb
module SearchHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/users/_list.html.erb
<div class="col-md-3 mt-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: '100x100'%>
  <%# フォローボタン %>
  <div class="row mt-3">
    <% unless user == current_user %>
    <div class="btn btn-outline-primary btn-block">
        <% if current_user.followings?(user) %>
          <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %>
        <% else %>
          <%= link_to "Follow", user_relationships_path(user.id), method: :post  %>
        <% end %>
    </div>
    <% end %>
  </div>

  <%# チャットボタン %>
  <div class="row mt-3 ">
    <% unless user.id == current_user.id %>
    <% if (current_user.followed_by? user) && ( user.followed_by? current_user)  %>
    <% if isRoom == true %>
    <p class="user-show-room btn btn-outline-primary btn-block text-center"><a href="/rooms/<%= roomId %>">チャット</a><p>
     <% else %>
      <%= form_with model: room do |f| %>
      <%= fields_for entry do |e| %>
      <%= e.hidden_field :user_id, value: user.id %>
      <% end %>
      <%= f.submit "チャットを始める" ,class:"btn btn-primary btn-lg user-show-chat"%>
      <% end %>
      <% end %>
      <% end %>
    <% end %>
  </div>
  <%# ユーザー情報 %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>intoduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>Follows</th>
        <th><%= link_to user_followings_path(user) do %><%= user.followings.count %><% end %></th>
      </tr>
      <tr>
        <th>Followers</th>
        <th><%= link_to user_followers_path(user) do %><%= user.followers.count %><% end %></th>
      </tr>
    </tbody>
  </table>
  <%# ユーザー編集 %>
  <div class="row">
    <div class="btn btn-outline-secondary btn-block"><%= link_to edit_user_path(user) do %><i class="fas fa-user-cog"></i><% end %></div>
  </div>
  <%# 投稿フォーム　%>
  <div>
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book, local:true do |f| %>
    <label for="book_title">Title</label>
      <div><%= f.text_field :title, class: "form-control" %></div>

    <label for="book_opinion">Opinion</label>
      <div><%= f.text_area :body, class: "form-control"  %></div>

    <label for="book_category">Category</label>
      <div><%= f.text_area :category, class: "form-control"  %></div>

    <div class="mt-3" id="book_rate">
      <label for="book_rate">Rate</label>
    </div>
    <script>
     $('#book_rate').empty();
      $('#book_rate').raty({
        starOn: "<%= asset_path('star-on.png')  %>",
        starOff: "<%= asset_path('star-off.png')  %>",
        starHalf: "<%= asset_path('star-half.png')  %>",
        scoreName: "book[rate]",
        half: true,
      });
    </script>
    <div class="text-center">
      <button class="btn btn-success mt-3 "><% f.submit %>Create Book</button>
    </div>
    <% end %>
  </div>
</div>

bookers2/app/views/users/edit.html.erb
<div class="container">
  <%= render "layouts/errors" , obj: @user %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
       <div>
        <div><label for="inputName">Name</label></div>
        <div><%= f.text_field :name, placeholder:"名前" , class: "form-control" %></div>
       </div>
       <div>
        <div><label for="inputImage">Image</label></div>
        <div><%= f.attachment_field :profile_image, placeholder: "image", class: "form-control-file"  %></div>
       </div>
       <div>
        <div><label for="inputIntroduction">Introduction</label></div>
         <div><%= f.text_area :introduction , class: "form-control" %></div>
       </div>
       <button class="btn btn-success mt-2"><% f.submit %>Update User</button>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/header', user: @user %>
  <div class="row mt-3">
    <%= render 'users/list',user: @user, book: @book %>
    <div class="col-md-8 offset-md-1 mt-3 pr-4">
      <h2>Users</h2>
      <span><%= link_to "グループを作成する", new_group_path %></span>
      <span>|</span>
      <span><%= link_to "グループ一覧", groups_path %></span>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user|%>
          <tr>
            <td><%= attachment_image_tag user, :profile_image,:fill,100,100, format: 'jpeg', fallback: "no_image.jpg",size: '40x40' %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数：<%= user.followers.count  %></td>
            <td>
             <% unless user == current_user %>
                <% if current_user.followings?(user) %>
                  <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete,class: "btn btn-primary btn-sm"  %>
                <% else %>
                  <%= link_to "Follow", user_relationships_path(user.id), method: :post,class: "btn btn-primary btn-sm"  %>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to "Show", user_path(user) %> </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row ml-3">
    <%= render 'users/list',user: @user, book: @book, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry %>

    <div class="col-md-8 offset-md-1 mt-3 pr-4">
      <h2>Books</h2>
      <%= render "books/index", books: @books %>
    </div>
    <div class="col-md-10 offset-md-1 mt-3">
      <div class="table-width mt-4">
        <h4>投稿の前日比・前週比</h4>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @book_today.count %></td>
              <td><%= @book_yesterday.count %></td>
              <td>
                <% if @book_yesterday.count == 0 %>
                  <p>0</p>
                <% else %>
                  <% @day_before_ratio = @book_today.count / @book_yesterday.count.to_f %>
                  <%= (@day_before_ratio * 100).round(2) %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table-width mt-4">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>前週の投稿数</th>
              <th>前週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @book_this_week.count %></td>
              <td><%= @book_last_week.count %></td>
              <td>
                <% if @book_last_week.count == 0 %>
                  <p>0</p>
                <% else %>
                  <% @week_ratio = @book_this_week.count / @book_last_week.count.to_f %>
                  <%= (@week_ratio * 100).round(2) %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>