bookers2/config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  get '/search/:category' => 'search#search_category',as: 'search_category'
  get '/search_date' => 'search#search_date',as: 'search_date'

  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/top' => 'homes#top'
  get '/home/about' => 'homes#about'

  resources :books,only:[:create,:index,:edit,:update,:destroy,:show] do
    resources :book_comments,only:[:create,:destroy]
    resource :favorites,only:[:create,:destroy]
 end

  resources :users,only:[:show,:index,:edit,:update,:destroy] do
    resource :relationships,only:[:create,:destroy]

    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end

 resources :groups do
   resources :group_users,only:[:create,:destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
 end

 resources :messages, only:[:create]
 resources :rooms, only:[:create,:show]
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  is_impressionable counter_cache: true

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user, dependent: :destroy
  validates :title,presence: true
  validates :body,presence: true, length: { maximum: 200 }
 


def favorite_by?(user)
  favorites.where(user_id: user.id).exists?
end

scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }

scope :created_2days_ago, -> { where(created_at: 2.day.ago.all_day) }
scope :created_3days_ago, -> { where(created_at: 3.day.ago.all_day) }
scope :created_4days_ago, -> { where(created_at: 4.day.ago.all_day) }
scope :created_5days_ago, -> { where(created_at: 5.day.ago.all_day) }
scope :created_6days_ago, -> { where(created_at: 6.day.ago.all_day) }


scope :created_this_week, -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)}
scope :created_last_week, -> {where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day)}
end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment ,presence: true
end

bookers2/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2/app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  attachment :image

  def joined_by?(user)
    group_users.where(user_id: user.id).exists?
  end

end

bookers2/app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

bookers2/app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :content ,presence: true, length: { maximum: 200 }
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers2/app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many:entries, dependent: :destroy
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users
  has_many :groups,through: :group_users
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy


  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

  def followed_by?(user)
    followers.include?(user)
  end


  scope :created_this_week, -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)}

  attachment :profile_image

  validates :name,presence: true, length: { minimum: 2 , maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

impressionist :actions=> [:show,:index]

  def show
    @book_s = Book.new
    @book = Book.find(params[:id])
    impressionist(@book, nil, unique: [:ip_address])
    @user = User.find(current_user.id)
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @user = User.find(current_user.id)


    if params[:sort_new]
      @books = Book.order(created_at: "desc")
    elsif params[:sort_rate]
      @books= Book.order(rate: "DESC")
    elsif params[:sort_rank]
      @books = Book.order(impressions_count: "DESC")
    else
      @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    flash[:notice]= "You have created book successfully"
    else
    @books = Book.all
    @user = User.find(current_user.id)
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice]= "You have updated book successfully"
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to user_path(book.user)
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:rate,:category)
  end


end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/group_users_helper.rb
module GroupUsersHelper
end

bookers2/app/helpers/groups_helper.rb
module GroupsHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/messages_helper.rb
module MessagesHelper
end

bookers2/app/helpers/rooms_helper.rb
module RoomsHelper
end

bookers2/app/helpers/search_helper.rb
module SearchHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_comment.html.erb
      <h4>Comment</h4>
      <table class="table">
        <tbody >
          <% book.book_comments.each do |book_comment| %>
          <tr>
            <td>
             <div><%= attachment_image_tag book_comment.user,:profile_image,:fill,50,50, fallback: "no_image.jpg",size: "50x50" %></div>
             <div>
              <%= link_to user_path(book.user_id) do %>
               <%= book_comment.user.name %>
              <% end %>
             </div>
            </td>
            <td><%= book_comment.comment %></td>
            <td><% if book_comment.user == current_user %>
              <button type="button" class="btn btn-danger btn-sm">
                <%= link_to "destroy", book_book_comment_path(book,book_comment), method: :delete,remote: true, class: "text-white"%>
              </button>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= form_with model: [book,book_comment] do |f| %>
      <div class="field">
        <%= f.text_area :comment, size: "60x5",rows:'5'%>
        <%= f.submit "送信" %>
      </div>
      <% end %>
    </div>
  </div>

bookers2/app/views/books/_date.html.erb
<div class="col-xs-6 col-xs-offset-3 text-center" style="margin-top: 25px;">
 <h4>検索結果</h4>
  <table class="table">
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= book_count %></td>
      </tr>
    </tbody>
  </table>
</div>

bookers2/app/views/books/_index.html.erb
     <%# 詳細テーブル %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th>いいね数</th>
            <th>コメント数</th>
            <th>Rate</th>
            <th>閲覧数</th>
          </tr>
        </thead>
        <tbody>
          <% books.each do |book| %>
          <td>
            <%# ユーザー画像 %>
            <td><%= link_to user_path(book.user_id) do %><%= attachment_image_tag book.user, :profile_image,:fill,100,100,format: 'jpeg', fallback: "no_image.jpg",size: '40x40' %>
             <% end %>
            </td>
            <%# タイトル　詳細へのリンク付き %>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %></td>
              <% end %>

            <%#　本の説明  %>
            <td><%= book.body %></td>

            <%# カテゴリー　絞り込みリンク付き %>
            <td>
              <% unless book.category.nil?  %>
                <%= link_to search_category_path(category: book.category) do %>
                  <%= book.category %>
                <% end %>
              <% end %>
            </td>

            <%# ファボ数 %>
            <td id ="book_favorites_<%= book.id %>">
              <%= render 'favorites/favorite',book: book %>
            </td>
            <%# コメント数 %>
            <td><%= book.book_comments.count %></td>
            <%# ランク数 %>
            <td class="book_rate_<%= book.id  %>" data-score="<%= book.rate %>"></td>
            <%# 閲覧数 %>
            <td><%= book.impressions_count %></td>
          </tr>
          <%# jquery.raty.js %>
          <script>
          $('.book_rate_<%= book.id  %>').empty();
            $('.book_rate_<%= book.id  %>').raty({
              readOnly: true,
              score: function(){
                return $(this).attr('data-score');
              },
              path: '/assets/'
            });
          </script>
          <% end %>
        </tbody>
      </table>
      <div class="row" >
        <div　class="col-xs-6 col-xs-offset-3 text-center" style="margin-top: 25px;">
          <%= form_with url:search_date_path, method: :get, local: false do |f|  %>
           <%= f.date_field :created_at %>
           <%= f.submit:"検索" %>
          <% end %>
        </div>
        <div id="book_dates">
         
        </div>
      </div>

bookers2/app/views/books/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render "layouts/errors", obj: @book %>
      <div>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <div><%= f.text_field :title, autofocus: true, id:"book_title" , class: "form-control" %></div>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <div><%= f.text_area :body, id:"book_body" , class: "form-control" %></div>
        </div>
        <div class="form-group">
         <label for="book_category">Category</label>
         <div><%= f.text_area :category, class: "form-control"  %></div>
        </div>

        <div id="book_rate">
          <label for="book_rate">Rate</label>
        </div>

        <script>
          $('#book_rate').raty({
            starOn: "<%= asset_path('star-on.png')  %>",
            starOff: "<%= asset_path('star-off.png')  %>",
            starHalf: "<%= asset_path('star-half.png')  %>",
            scoreName: "book[rate]",
            half: true,
          });
        </script>

        <div class="form-group">
          <button class="btn btn-success">
          <% f.submit %>Update Book</button>
        </div>
          <% end %>
      <div>
          <sapn><%= link_to "Show", book_path(@book)  %></sapn>
          <span>|</span>
          <span><%= link_to "Back", books_path %></span>
        </div>
      </div>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors',obj: @book %>
  <%= render 'layouts/header',user: @user%>
  <div class="row ml-3">
  <%= render 'users/list',user: @user, book: @book %>

    <div class="col-md-8 offset-md-1 mt-3 pr-4">
      <h2>Books</h2>
      <%= link_to "新しい順",books_path(sort_new: "true") %>｜<%= link_to "評価の高い順" ,books_path(sort_rate: "true") %>｜<%= link_to"閲覧数の多い順" , books_path(sort_rank: "true")%>
      <%= render "books/index", books: @books %>
    </div>
    <div class="col-md-10 offset-md-1 mt-3">
      <h4>7日分の投稿数</h4>
      <table class="table">
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @books.created_6days_ago.count %></td>
            <td><%= @books.created_5days_ago.count %></td>
            <td><%= @books.created_4days_ago.count %></td>
            <td><%= @books.created_3days_ago.count %></td>
            <td><%= @books.created_2days_ago.count %></td>
            <td><%= @books.created_yesterday.count %></td>
            <td><%= @books.created_today.count %></td>
          </tr>
        </tbody>
      </table>
      <canvas id="myLineChart" width="300" height="100"></canvas>
      <script>
        var ctx = document.getElementById("myLineChart").getContext('2d');
        var myChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
              label: "本の投稿数",
              data: [<%= @books.created_6days_ago.count %>, <%= @books.created_5days_ago.count %>, <%= @books.created_4days_ago.count %>, <%= @books.created_3days_ago.count %>, <%= @books.created_2days_ago.count %>, <%= @books.created_yesterday.count %>, <%= @books.created_today.count%>],
              backgroundColor: 'rgba(255, 80, 120, 1.0)',
              borderColor: 'rgba(255, 80, 120, 1.0)',
              fill: false
              }]
            },
          });
      </script>
    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors',obj: @book_comment%>
  <div class="row mt-3">

    <%= render 'users/list',user: @user, book: @book_s %>
    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Book detail</h2>
      <table class="table table-striped">
       <tbody>
         <tr>
          <td>
           <div><%= attachment_image_tag @book.user,:profile_image,:fill,50,50 %></div>
           <div><%= link_to user_path(@book.user_id) do %>
           <%= @book.user.name %>
           <% end %>
           </div>
          </td>
          <td>
          <%= link_to book_path(@book) do %>
          <%= @book.title %>
          <% end %>
          </td>
          <td><%= @book.body %></td>
          <td><%= @book.category %></td>
          <td id ="book_favorites_<%= @book.id %>">
            <%= render "favorites/favorite", book: @book %>
          </td>
          <td>コメント数:<%= @book.book_comments.count %></td>
          <td class="book_rate_<%= @book.id  %>" data-score="<%= @book.rate %>"></td>
          <td>閲覧数:<%= @book.impressions_count %></td>

          <% if @book.user_id == current_user.id %>
           <td><span class="btn btn-sm btn-success btn-sm"><%= link_to "Edit", edit_book_path(@book)%></span></td>
           <td><span class="btn btn-sm btn-danger btn-sm"><%= link_to "Destroy", book_path(@book),method: :delete, "data-confirm"=> "Do you really want to delete this book？" %></span></td>
          <% end %>
       </tbody>
       <script>
          $('.book_rate_<%= @book.id  %>').empty();
            $('.book_rate_<%= @book.id  %>').raty({
              readOnly: true,
              score: function(){
                return $(this).attr('data-score');
              },
              path: '/assets/'
            });
          </script>
      </table>
      <div id ="book_comments_index" >
      　<%= render "book_comments/comment", book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>